### ISSUE TITLE
Diff in jasmine.objectContaining

### ISSUE THREAD

**Issue by adavidof** [mradionov/karma-jasmine-diff-reporter#16]
When we compare:
`expect(res).toEqual(jasmine.objectContaining(result));`

And when only one key have not the same we can see 2 or above differences

Thanks :)

![image](https://cloud.githubusercontent.com/assets/10529679/17095078/6acc0cea-525b-11e6-88ae-2604abff6447.png)

**Comment by mradionov** [comment]
To be honest I don't really understand what is happening on your screenshot, because compared objects are too big. I guess there is a problem with `jasmine.objectContaining()` and reporter does not highlight it correctly. I am not sure what will be a correct behavior for it yet, maybe it will be better to disable highlighting for `jasmine.objectContaining()` at all because of it's nature, I'll play around with it a bit and come back. It would be great if you could provide an example of your problem with smaller objects, so I could reproduce it. Thanks!

**Comment by adavidof** [comment]
Look at this:
![image](https://cloud.githubusercontent.com/assets/10529679/17178243/561c1e0c-541d-11e6-8020-6d97f66440ba.png)

`order` value the same like in jasmine.objectContaining `order`, but it matched like not the same(red color)

I hope I help you :)

**Comment by mradionov** [comment]
Thank you, that helps a lot. So the problem is not even with `jasmine.objectContaining()`, but in the order of object properties. Unfortunately I don't think it can be properly fixed, because JavaScript does not guarantee the order of object properties at least in ES5 ([more info on SO](http://stackoverflow.com/questions/5467129/sort-javascript-object-by-key)). Also, objects themselves are  not available to me from inside the reporter, I only operate error messages from Jasmine, where objects have already been converted to a string. It would be very complex to try to parse and recreate original objects from their string representation.

I'll spend some more time and try to find something else I could possibly do. Thanks!

**Comment by mradionov** [comment]
I've added object sorting before objects are passed to pretty printer according to [this SO answer](http://stackoverflow.com/a/29622653/1573638), properties will be sorted in alphabetical order and as a result reporter should not highlight same props twice. 

Grab the latest version [0.6.1](https://www.npmjs.com/package/karma-jasmine-diff-reporter) to get the fix. Thanks for your contribution.

I'll keep this issue open for a while, because I also want to think about `jasmine.objectContaining()`, it's still an open question for me.

**Comment by mradionov** [comment]
I've decided to not highlight diffs when using `jasmine.objectContaining()` at all.
This fix is available in [0.6.2](https://www.npmjs.com/package/karma-jasmine-diff-reporter)

**Comment by adavidof** [comment]
@mradionov Why you do this?

**Comment by mradionov** [comment]
Because resulting output can't be correctly compared. Most of the times when one uses `jasmine.objectContaining()`, the actual object is usually big, and the `jasmine.objectContaining()` contains one or few properties to check. See an example:

```
var a = {
  foo: 42,
  bar: 43,
  baz: 44,
  qux: 45
};
expect(a).toEqual(jasmine.objectContaining({ foo: 43 }));
```
![image](https://cloud.githubusercontent.com/assets/2007370/17457377/0c823580-5bff-11e6-964d-1b134bd62c94.png)

The result is very misleading, because it highlights the entire "actual" part in green like these are new properties comparing to "expected" part, but they are not. They are highlighted in green only because of the nature of  `jasmine.objectContaining()` - it simply does not display the rest of the object, but only that one property that we need. And it affects the resulting diff a lot, and red/green colors are not useful at all in this case. I've decided not to add colors, because they might bring even more confusion, if there were no any colors at all.

![image](https://cloud.githubusercontent.com/assets/2007370/17457403/f129a696-5bff-11e6-859c-6a2dd44b86f8.png)

Please let me know if you have different thoughts about it, maybe you also have some examples, when it is really useful.

**Comment by adavidof** [comment]
@mradionov 

> I've decided not to highlight diffs when using jasmine.objectContaining() at all.

I think it would be better with it

For example:
You have object:
`var x = {
a: 1,
b: 2,
c: 3
}`

and comparing object:
`var y = {
a: 1
}`

If you do the comparing with jasmine.objectContaining it would be ok:
`except(x).toEqual(jasmine.objectContaining(y));`

If you change data like this:
`var x = {
a: 1,
b: 2,
c: 3
};

var y = {
a: 1,
b: 5
}`

And try to compare:
`except(x).toEqual(jasmine.objectContaining(y));`

You have the difference, and I think it would be really awesome if you can find the difference
But now you disable this option

It's a good feature and please give it for us

If you don't want to turn it on, you can do the options with which we can turn on/off feature

Thanks

**Comment by adavidof** [comment]
@mradionov 
So what about the option to turn it on/off?

**Comment by mradionov** [comment]
Is it ok if I bring it back as it worked before? Even thought it was baggy.
Unfortunately I have very little free time now, but I am slowly working on an improved version of the reporter, where I hope it will be possible to correctly show diffs for `jasmine.objectContaining`

**Comment by mgol** [comment]
> Is it ok if I bring it back as it worked before? Even thought it was baggy.

I think that's better than not seeing anything at all. :)

BTW, how did you get the objects to be displayed in multiple lines as in your screenshot? I've only seen the all-in-one-line way in Jasmine when comparing objects.

**Comment by mradionov** [comment]
That's a pretty print option of the reporter, check it in the docs - https://github.com/mradionov/karma-jasmine-diff-reporter#pretty-print

**Comment by mradionov** [comment]
I've reverted the fix, `jasmine.objectContaining` should be highlighted as before in [0.6.3](https://www.npmjs.com/package/karma-jasmine-diff-reporter)

**Comment by adavidof** [comment]
@mradionov 
Cool, thanks :)

**Comment by mradionov** [comment]
Fixed. `jasmine.objectContaining` now should be highlighted much better in [1.0.0](https://github.com/mradionov/karma-jasmine-diff-reporter/releases/tag/v1.0.0), make sure to check it out! 
Feel free to reopen or create a new issue if you encounter anything weird. Thanks!
