### ISSUE TITLE
Default colors suggestion

### ISSUE THREAD

**Issue by fritz-c** [mradionov/karma-jasmine-diff-reporter#19]
Perhaps it's only due to my terminal settings, but I couldn't use the reporter with its out-of-the-box color configuration.

It looked like this:
![2016-08-25 13 57 37](https://cloud.githubusercontent.com/assets/4413963/17957392/4790c6d8-6acc-11e6-8a87-ade0b8442dd1.png)

I changed my color configuration to the following:

``` js
color: {
    actualFg: 'red',
    expectedFg: 'green',
    actualBg: 'inverse',
    expectedBg: 'inverse',
    actualWhitespaceBg: '',
    expectedWhitespaceBg: '',
}
```

And it looked like this.
![2016-08-25 13 57 51](https://cloud.githubusercontent.com/assets/4413963/17957423/879d5eda-6acc-11e6-8254-6fb295a40a7e.png)

I believe the `inverse` setting is a better choice by virtue of it using the terminal's default background color as its foreground color. The background color generally would have high contrast next to colors such as green and red, as text rendered in green and red would have to be visible against the background in the first place.

**Comment by fritz-c** [comment]
On a side note, in your colors config section in the README, you have a comment
```js
actualBg: '',          // default 'bgGreen'
```
stating that the `actualBg` default is `bgGreen`, when in fact I think the default is the opposite of that (`bgRed`).

**Comment by mradionov** [comment]
It's hard to pick one correct color, because everybody has their own terminal preferences. Somebody has light green colors as you do, which looks better with dark text, on the other hand somebody has dark green colors, which look better with light text. So it's very subjective, I prefer not to change it. Good thing that it's configurable.

And regarding README - everything seems to be ok, color for "actual" is green. I guess what bring the confusion is that some Jasmine matchers display "actual" and "expected" in different order depending on how the matcher sentence is phrased. For example for `toBe` or `toEqual` matchers:

```
Expected "foo" to be "bar".
```

`foo` is "actual" and `bar` is "expected", because we "Expect **something that we have** to be **something we expect it to be**. And matchers like `toHaveBeenCalledWith`, `toThrow` and `toThrowError` have "actual" and "expected" in reversed order.
