### ISSUE TITLE
Colors not working but Pretty is

### ISSUE THREAD

**Issue by coreysnyder** [mradionov/karma-jasmine-diff-reporter#21]
I'm using the packages below and while `pretty` works, the colors do not. I have tried pruning down my karma file to only include the bare essentials and to no avail the colors wouldn't show up. 

```
    "grunt-karma": "^2.0.0",
    "jasmine-core": "^2.2.0",
    "karma-jasmine-diff-reporter": "^0.6.2"
```

```
var web_dependencies = require('./web_dependencies');

module.exports = function(config) {
  config.set({
    frameworks: ['jasmine'],
    browsers: ['Chrome'],

    files: web_dependencies.concat([
      ...
    ]),

    ngHtml2JsPreprocessor: {
      stripPrefix: 'public',
      moduleName: 'templates'
    },

    reporters: ['jasmine-diff'],


    jasmineDiffReporter: {
      pretty: true
    },

    colors: true
  });
};
```

It's worth noting that my terminal window does show other colors:
<img width="497" alt="screen shot 2016-10-31 at 1 07 21 pm" src="https://cloud.githubusercontent.com/assets/17259723/19863555/04531910-9f6b-11e6-8b39-1ebcda64477a.png">

**Comment by mradionov** [comment]
Looks weird, I've tried to reproduce it by installing phantomjs, grunt-karma and running tests via grunt, because I thought grunt was a reason, but I still got colors displayed (using your karma.conf.js), so I am out of ideas.

![image](https://cloud.githubusercontent.com/assets/2007370/19869529/c655c380-9fbd-11e6-8b18-d05a1a7fcb53.png)

May I ask you to clone karma-jasmine-diff-reporter into a separate folder and run a demo? I hope it will help me identify whether it is a problem in your particular project setup or maybe your terminal just ignores colors or somewhere else.

```
$ git clone https://github.com/mradionov/karma-jasmine-diff-reporter.git
$ cd karma-jasmine-diff-reporter
$ npm install
$ npm start
```

I'll be waiting for the results, thanks!

**Comment by sajidali** [comment]
I just did these steps
```
$ git clone https://github.com/mradionov/karma-jasmine-diff-reporter.git
$ cd karma-jasmine-diff-reporter
$ npm install
$ npm start
```

And on my terminal colors worked fine, so may be it is due to terminal issue?

**Comment by coreysnyder** [comment]
I tried it too and the colors show up just fine. So it must be a problem w/ something with my project's configuration. =/

**Comment by mradionov** [comment]
@coreysnyder , Could you please tell me what Operation System are you on? And also a terminal you use. It would be  also really great if you could try to run your tests in another alternative terminal and let me know if you have the same result. I'll appreciate you help, because I am not sure what might be causing the problem.

**Comment by coreysnyder** [comment]
@mradionov I am on OSX 10.12.1

**Comment by ox-michaelradionov** [comment]
I've tried this on Mac in iTerm2, but still got colors... Could you please post the code for you Grunt task which runs karma? Maybe there are some extra settings which might influence the output, for example coverage reporters.

**Comment by mradionov** [comment]
I've tried this on Mac in iTerm2, but still got colors... Could you please post the code for you Grunt task which runs karma? Maybe there are some extra settings which might influence the output, for example coverage reporters.

**Comment by mradionov** [comment]
Unable to reproduce. Feel free to reopen if you'll have any new information or minimal setup to reproduce the issue.
You could try a new version of the reporter [1.0.0](https://github.com/mradionov/karma-jasmine-diff-reporter/releases/tag/v1.0.0) - maybe the issue will be resolved.
