### ISSUE TITLE
Cannot prettify objects in results

### ISSUE THREAD

**Issue by kylekatarnls** [mradionov/karma-jasmine-diff-reporter#26]
Hi,

I'm trying to display results like in the documentation:

(http://i.imgur.com/6TTlSmB.jpg)

Changing colors and verbose works well, but pretty has no effect. All the following settings display objects on only one line:

```js
pretty: true
```
```js
pretty: '\t'
```
```js
pretty: 2
```
```js
multiline: {
  before: 3,
  after: '\n',
  indent: '  '
}
```
```js
pretty: true,
multiline: true
```

Thanks for help.

**Comment by mradionov** [comment]
Could you please share your karma config and tell me what operation system and terminal you use?

**Comment by kylekatarnls** [comment]
No problem, it's open-source: https://github.com/kylekatarnls/momentum/blob/7b31a5024168e07f0a08bd630d4b13c6fa7f15ec/karma.conf.js

I run karma start in Git Bash (Windows)

**Comment by mradionov** [comment]
It would be great if you could also provide a specific test case source code, which is failing for you. In addition I'd like to note that only toEqual and toHaveBeenCalled matchers will be pretty-printed. If you've noticed it with toBe, than it's an expected behavior.

Also... Well... It turns out that Jasmine finally got it's own version of "pretty print" for objects, which is available from version [2.6.0](https://github.com/jasmine/jasmine/blob/master/release_notes/2.6.0.md), and you are using that same version. That would be the reason why you might not have an output, which was expected from my reporter. Now it will look like this:

```
Expected object to have properties
	    b: 43
	Expected object not to have properties
	    a: 42
	    at Object.<anonymous> (spec/test.test.js:3:27)
```

Here is original issue in Jasmine rep: https://github.com/jasmine/jasmine/issues/675 and respective PR https://github.com/jasmine/jasmine/pull/1163.

I have to think about what to do next, because I did not expect it to happen this soon and I've just recently completed a major rewrite of the reporter. Probably I'll just keep it as is, so it will work only with Jasmine versions prior 2.6, because I have no idea how they are gonna continue improving their diff output and it might be difficult to adapt to from my side.

Thank you for your report, if you really want to use this reporter at full capacity, the only thing for now is to downgrade Jasmine to 2.5, but I am not insisting on it in any ways, because Jasmine might have things fixed and improved in latest versions.

**Comment by mradionov** [comment]
Another option might be to introduce an option in my reporter to ignore new Jasmine 2.6 diff output and bring back old 2.5 output by monkey-patching Jasmine, what I already do anyways, but it will also allow reporter to continue working as before.

**Comment by kylekatarnls** [comment]
I always use toBe (seems more relevant to me to be strict in unit tests). I'll try right now with toEquals. What is the reason pretty is only available for toEqual and toHaveBeenCalled?

**Comment by mradionov** [comment]
It's because `toBe` and `toEqual` are different from the inside. Think of `toBe` as a `===`: when you use `toBe` to compare two different objects you'll always get failed test as a result, because `===` compares objects by reference. `toEqual` on the other hand does a deep comparison of each property of provided objects, basically it compares if two objects content is different instead of comparing if object itself it the same.
So, in case with `toBe` I've decided that there is no point to pretty print the whole object, if it is still gonna be compared by reference (it will be highlighted in warning orange color) - test fails because of the entire object.
With `toEqual` though it makes sense, because test fails because of particular property in the object, so pretty print provides a more clear way for a developer to find this property in the object output.

Speaking of primitive types it does not matter if you use `toBe` or `toEqual.`

**Comment by kylekatarnls** [comment]
OK, so I tried many things and it's OK, when using `toEqual` expected and actual are both objects, output is prettyfied. It make sense.

As you say in #27 output is very indented to the right, but now with every packages up to date it do the trick.

Thanks!
