### ISSUE TITLE
Show diff with toContain() method

### ISSUE THREAD

**Issue by kopach** [mradionov/karma-jasmine-diff-reporter#31]
There is jasmine's `toContain()` method which check whether string (or an array) is containing sub-string. Any chance to show diff highlighting for this?

I understand, that this will also show me highlighted extra characters of parent string, but this is very ok for me.  Even in this case, it vill be much easier for me to recognize the issue.

**Comment by mradionov** [comment]
Hey, I'll take a look. Thanks!

**Comment by mradionov** [comment]
Could you please provide an example of the test you want to highlight and how it can be useful for you?
I am not sure about adding highlight to `toContain` method, because I think that there is no point in calculating the diff between values, which are supposed to be different. Maybe if you give me an example, I will see why it matters. I might be missing something.

From what I see now, the result would be the following.

For strings:

```
Expected '**foobarbaz**' to contain '**qux**'.
```

**Comment by kopach** [comment]
Hi @mradionov, I agree in examples above this highlighting is probably not useful, but still highlighting not adding any bad experience. Anyway, this highlighting becomes very useful in case of bigger data set. E.g. for such string 

```
Dummy text: Its function as a filler or as a tool for comparing the visual impression of different typefaces. Dummy text is text that is used in the publishing industry or by web designers to occupy the space which will later be filled with 'real' content.
```

If I would expect to have such text in it: `Dummy text - is text that is used in the publishing industry`

I would be very useful to see, that test is failing because there is no dash sign `-` in tested string. Without highlighting such small things quite difficult to determine (especially, when there are few of such "typos".

**Comment by mradionov** [comment]
It can be somewhat applied to strings, because the library I use for calculating diffs, allows to compare strings and highlight how these strings differ. The results won't be accurate for array though.

I took your sample string as an example and applied a diff for it. Here is what I've got:

![image](https://user-images.githubusercontent.com/2007370/38801588-e9a59e7a-4172-11e8-8abb-faaab49b578f.png)

From my point of view the diff is incorrect. As a developer I would expected that the second sentence will be highlighted against expected result, but it would be very difficult to achieve We don't have complete strings on both sides of the equation -  first one is a complete string, second one is a sub-string we a trying to locate inside the first one. The diff library is simply comparing string, is does not try to find a sub-string and create a diff specifically for it. Having said that, I am not sure it should be added to the reporter out of the box, but I can suggest an option just for you.

Reporter configuration provides an option `customMatchers`, where you can add highlighting to matchers, which are not supported out of the box.

```
jasmineDiffReporter: {
  matchers: {
    toContain: {
      pattern: /Expected ([\S\s]*?) to contain ([\S\s]*?)\./,
      reverse: true
    }
  }
}
```


If you use this configuration it will simply highlight entire values.

![image](https://user-images.githubusercontent.com/2007370/38801972-ec873670-4173-11e8-9798-fec1de7431d6.png)

But I can improve it a bit so you could choose which type of diff will be performed for a custom matcher, so the values can be compared as strings and you could see which parts of strings are in conflict.

![image](https://user-images.githubusercontent.com/2007370/38801588-e9a59e7a-4172-11e8-8abb-faaab49b578f.png)

Please let me know if the option of using custom matcher works for you. I'll then add a improvement for it so you could select diff algorithm and release as a new minor version of the reporter.

**Comment by kopach** [comment]
The solution with custom matcher patter sounds perfect for me as long as I could get conflicted parts of the string.

**Comment by mradionov** [comment]
The result will be the same as on the screenshot (for provided sample):

![image](https://user-images.githubusercontent.com/2007370/38803148-fd7cec2e-4176-11e8-8aae-f068ca41f506.png)

If this result is ok for you, then I'll be happy to help.

**Comment by kopach** [comment]
Yes, this is super perfect and would help me a lot. Thank you 🙇 . Can't wait for this patch release 🎉

**Comment by mradionov** [comment]
Support for selecting an diff algorithm for custom matcher has been added to a release [1.2.0](https://github.com/mradionov/karma-jasmine-diff-reporter/releases/tag/v1.2.0), release has been publish to [npm](https://www.npmjs.com/package/karma-jasmine-diff-reporter).

Docs for configuring custom matchers has been extended with information about possible value for new `format` option ([docs](https://github.com/mradionov/karma-jasmine-diff-reporter#matchers)).

@kopach , to enable highlighting for `toContain` matcher as string, you should add the following configuration to your karma config file:

```
jasmineDiffReporter: {
  matchers: {
    toContain: {
      format: 'primitive',
      pattern: /Expected ([\S\s]*?) to contain ([\S\s]*?)\./,
      reverse: true
    }
  }
}
```
