### ISSUE TITLE
DEPRECATION: jasmine.matchersUtil is deprecated and will be removed in a future release

### ISSUE THREAD

**Issue by Den-dp** [mradionov/karma-jasmine-diff-reporter#64]
The following deprecation notice is shown when I use this reporter:

```
DEPRECATION: jasmine.matchersUtil is deprecated and will be removed in a future release. Use the instance passed to the matcher factory or the asymmetric equality tester's `asymmetricMatch` method instead. See <https://jasmine.github.io/tutorials/upgrading_to_Jasmine_4.0#static-utils> for details.
    at <Jasmine>
    at matchersUtilPatched (http://localhost:9876/base/node_modules/karma-jasmine-diff-reporter/src/karma-jasmine/util-patch.js?24ebf18c87e51712a9f46a9365bf0873ee5ebc85:11:17)
    at http://localhost:9876/base/node_modules/karma-jasmine-diff-reporter/src/karma-jasmine/util-patch.js?24ebf18c87e51712a9f46a9365bf0873ee5ebc85:8:31
    at http://localhost:9876/base/node_modules/karma-jasmine-diff-reporter/src/karma-jasmine/util-patch.js?24ebf18c87e51712a9f46a9365bf0873ee5ebc85:28:2
Note: This message will be shown only once. Set the verboseDeprecations config property to true to see every occurrence.'
```
![image](https://user-images.githubusercontent.com/1770529/217889202-f5079c0f-accc-44a1-98aa-6582b2e2740e.png)

**Comment by jtowe1** [comment]
Same here

**Comment by mradionov** [comment]
Hey, what Jasmine version do you use?

**Comment by mradionov** [comment]
Oh, it's 3.99, I see. Does it fail your test or does it just show the deprecating warning?

**Comment by Den-dp** [comment]
@mradionov luckily this doesn't break the tests - only the deprecation notice is shown everywhere, so I decided to inform you

**Comment by mradionov** [comment]
It's the version of `jasmine-core` 3.99 and 3.99.1 specifically where they've added these deprecation warnings (https://github.com/jasmine/jasmine/blob/main/release_notes/3.99.0.md). I can't do much about the warnings because I still need these functions for the reporter to work. And I can't use the new ones because the reporter relied heavily on the old ones - that's why I've decided to discontinue the reporter https://github.com/mradionov/karma-jasmine-diff-reporter/issues/63 as I can't support Jasmine 4+.

One thing I could suggest is to use the latest version of `jasmine-core` prior to 3.99, which is 3.10.1 - it must be the same functionality, but without the warnings.

I am going to close this, I don't have a clear fix for it, but thank you for letting me know.
